Feature part3
olgaKudina/automationpractice pull request #3
Opened 2021-07-19 16:13 UTC by olgaKudina

2021-07-20 16:41 UTC, vchesnakoutest requested changes
please make fixes

2021-07-20 16:41 UTC, vchesnakoutest commented on .gitignore
> +/target/'.idea'
папку target надо полностью исключать

2021-07-20 16:41 UTC, vchesnakoutest commented on src/main/java/pages/CatalogPage.java
> +    public static final By CATALOG_XPATH = By.xpath("//*[contains(text(),'Catalog')]");
CATALOG_TITLE_XPATH

2021-07-20 16:41 UTC, vchesnakoutest commented on src/main/java/pages/CatalogPage.java
> +    public String confirmCatalogName() {
getCatalogTitleText

2021-07-20 16:41 UTC, vchesnakoutest commented on src/test/java/tests/ProductsTest.java
> +        Assert.assertEquals(catalogPage.confirmCatalogName(), "CATALOG");
а что если у нас вместо Blouses откроется T-shirts ? Этот тест все равно будет зеленым и не найдет баг. Нам надо проверять, что именно страница  с "Blouses" открылась.

2021-07-20 16:41 UTC, vchesnakoutest commented on src/main/java/pages/CreateAccountPage.java
> +    public static final String NEW_ACCOUNT_CREATED_TEXT = "//*[contains(text(),'Welcome to your account. Here you can manage all of your personal information and orders.')]";
лучше привязываться к части текста, так будет меньше зависимости при его изменении. Например : Welcome to your account

2021-07-20 16:41 UTC, vchesnakoutest commented on src/main/java/pages/CreateAccountPage.java
> +        driver.findElement(REGISTER_BUTTON).click();
вообще в этом методе лучше использовать объектный паттерн, который мы использовали в SalesForce, когда для одинаковых элементов создается отдельный объект. Пока можешь оставить так, потом если останется время это можно будет передалать как улучшение.

2021-07-20 16:41 UTC, vchesnakoutest commented on src/main/java/pages/CreateAccountPage.java
> +    public String getAccountCreatedConfirmation(){
getCreatedAccountConfirmationText

2021-07-20 16:41 UTC, vchesnakoutest commented on src/main/java/pages/HeaderPage.java
> +    public static final By SEARCH_RESULT = By.xpath("//*[contains(text(),'result has been found')]");
search result это уже элемент страницы SearchPage 
![image](https://user-images.githubusercontent.com/48148401/126224296-e222bd4e-96b4-4807-8f8e-fd1f0171d5d7.png)

2021-07-20 16:41 UTC, vchesnakoutest commented on src/main/java/pages/HeaderPage.java
> +    public boolean getSearchResult() {
isSearchResultDisplayed. также этот метод должен находится на SearchPage

2021-07-20 16:41 UTC, vchesnakoutest commented on src/main/java/pages/HomePage.java
> +        driver.get(BASE_URL);
давай вынесем этот метод в BasePage и будем передавать ему url как параметр. А в этом и похожих остальных методах будешь вызывать super.openPage(BASE_URL)

2021-07-20 16:41 UTC, vchesnakoutest commented on src/main/java/pages/HomePage.java
> +        action.moveToElement(driver.findElement(By.xpath(String.format(PRODUCT_XPATH, productName)))).build().perform();
на будущее как улучшение: эту часть кода можно вынести в отдельный класс utils и создать статический метод moveToElement в который мы передадим драйвер и нужный локатор через параметры

2021-07-20 16:41 UTC, vchesnakoutest commented on src/main/java/pages/HomePage.java
> +        action.moveToElement(driver.findElement(By.xpath(String.format(PRODUCT_XPATH, productName)))).build().perform();
соотв. тут можно будет вызывать этот статический метод

2021-07-20 16:41 UTC, vchesnakoutest commented on src/main/java/pages/HomePage.java
> +        action.moveToElement(driver.findElement(By.xpath(String.format(PRODUCT_GROUP_XPATH, productGroupName)))).build().perform();
и тут тоже

2021-07-20 16:41 UTC, vchesnakoutest commented on src/main/java/pages/LoginPage.java
> +    public static final By LOGIN_WARNING = By.xpath("//*[@class='alert alert-danger']");
старайся привязывать только к одному классу через contains, наприм. alert-danger

2021-07-20 16:41 UTC, vchesnakoutest commented on src/main/java/pages/LoginPage.java
> +    public static final By SIGNUP_BUTTON_XPATH = By.xpath("//*[@class='login']");
этот элемент и метод, кот. его использует должен быть в HeaderPage

2021-07-20 16:41 UTC, vchesnakoutest commented on src/main/java/pages/LoginPage.java
> +        driver.findElement(SIGNUP_BUTTON_XPATH).click();
это надо вынести в отдельный метод на HeaderPage

2021-07-20 16:41 UTC, vchesnakoutest commented on src/main/java/pages/LoginPage.java
> +        driver.findElement(SUBMIT_LOGIN_BUTTON).click();
надо ещё добавить лог на клик

2021-07-20 16:41 UTC, vchesnakoutest commented on src/main/java/pages/LoginPage.java
> +        driver.get(BASE_URL);
используй открытие страницы через общий метод в BasePage

2021-07-20 16:41 UTC, vchesnakoutest commented on src/main/java/pages/LoginPage.java
> +        driver.findElement(SIGNUP_BUTTON_XPATH).click();
этот здесь надо удалить и использовать в тестах метод из HeaderPage

2021-07-20 16:41 UTC, vchesnakoutest commented on src/main/java/pages/LoginPage.java
> +        driver.findElement(SUBMIT_LOGIN_BUTTON).click();
лог на клик

2021-07-20 16:41 UTC, vchesnakoutest commented on src/main/java/pages/LoginPage.java
> +    @Step("Warning message is displayed if Password is incorrect")
"Get warning message is displayed if Password is incorrect

2021-07-20 16:41 UTC, vchesnakoutest commented on src/main/java/pages/LoginPage.java
> +        driver.findElement(SIGNUP_BUTTON_XPATH).click();
также эту часть надо отсюда вынести

2021-07-20 16:41 UTC, vchesnakoutest commented on src/main/java/pages/LoginPage.java
> +        log.info("Enter random email", EmailGenerator.getSaltString() + "@mail.net");
полученное из EmailGenerator.getSaltString() надо записывать в переменную, а потом её вызывать тут и дальше в действии.

2021-07-20 16:41 UTC, vchesnakoutest commented on src/main/java/pages/PaymentMethodPage.java
> +    public OrderSummaryPage choosePaymentMethod() {
chooseBankWirePaymentMethod

2021-07-20 16:41 UTC, vchesnakoutest commented on src/main/java/utils/WaitForElement.java
> +public class WaitForElement {
отдельный класс для вейтеров это хорошо 👍

2021-07-20 16:41 UTC, vchesnakoutest commented on src/test/resources/allure.properties
> +allure.link.tms.pattern=https://github.com/{}
эти можно удалить

2021-07-20 16:41 UTC, vchesnakoutest commented on src/test/java/tests/SigninTest.java
> +        Assert.assertEquals(createAccountPage.getAccountCreatedConfirmation(), "Welcome to your account. Here you can manage all of your personal information and orders.");
в этом тесте ещё необходимо проверять, что имя пользователя отображается в шапке сайта

2021-07-22 20:57 UTC, olgaKudina commented on src/main/java/pages/LoginPage.java
> +        driver.findElement(SUBMIT_LOGIN_BUTTON).click();
лог добавила

2021-07-22 21:01 UTC, olgaKudina commented on src/main/java/pages/HomePage.java
> +        driver.get(BASE_URL);
base page у меня абстрактный класс, поэтому когда я туда добавила метод openPage(url) и применила openPage в Steps, начало ругаться. 
тогда похоже придется делать base page public, а не абстрактным

2021-07-22 21:02 UTC, olgaKudina commented on src/main/java/pages/CreateAccountPage.java
> +    public static final String NEW_ACCOUNT_CREATED_TEXT = "//*[contains(text(),'Welcome to your account. Here you can manage all of your personal information and orders.')]";
когда удалила второе предложение, тест начал падать и ругаться.

2021-07-26 20:12 UTC, olgaKudina reviewed
Fixed

2021-07-26 20:12 UTC, merged